create table if not exists ai_usage_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  feature text not null,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_events_owner_created_idx
  on ai_usage_events(owner_id, created_at desc);

alter table ai_usage_events enable row level security;
revoke all on ai_usage_events from anon, authenticated;
