create table if not exists record_revisions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  record_type text not null check (record_type in ('comment', 'behavior')),
  student_id bigint not null,
  subject text not null default '',
  content text not null,
  characteristic text not null default '',
  confirmed boolean not null default false,
  source text not null,
  created_at timestamptz not null default now()
);

create index if not exists record_revisions_lookup_idx
  on record_revisions(owner_id, class_id, record_type, student_id, subject, created_at desc);

alter table record_revisions enable row level security;
revoke all on record_revisions from anon, authenticated;
