create table if not exists assessment_plan_versions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  source text not null,
  label text not null,
  plan jsonb not null default '[]'::jsonb,
  item_count integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists assessment_plan_versions_lookup_idx
  on assessment_plan_versions(owner_id, class_id, created_at desc);

alter table assessment_plan_versions enable row level security;
revoke all on assessment_plan_versions from anon, authenticated;

insert into assessment_plan_versions(owner_id, owner_email, class_id, source, label, plan, item_count, created_at)
select
  classrooms.owner_id,
  classrooms.owner_email,
  classrooms.id,
  'initial',
  '기존 평가계획',
  coalesce(jsonb_agg(
    jsonb_build_object(
      'subject', assessment_plans.subject,
      'unit', assessment_plans.unit,
      'goal', assessment_plans.goal,
      'domain', assessment_plans.domain,
      'assessment_type', assessment_plans.assessment_type,
      'perspective', assessment_plans.perspective,
      'high', assessment_plans.high,
      'middle', assessment_plans.middle,
      'low', assessment_plans.low,
      'caution', assessment_plans.caution,
      'sort_order', assessment_plans.sort_order
    ) order by assessment_plans.sort_order
  ) filter (where assessment_plans.id is not null), '[]'::jsonb),
  count(assessment_plans.id),
  now()
from classrooms
left join assessment_plans on assessment_plans.class_id = classrooms.id and assessment_plans.owner_id = classrooms.owner_id
where classrooms.owner_id is not null
  and not exists (
    select 1 from assessment_plan_versions
    where assessment_plan_versions.owner_id = classrooms.owner_id
      and assessment_plan_versions.class_id = classrooms.id
  )
group by classrooms.id, classrooms.owner_id, classrooms.owner_email;

create or replace function restore_assessment_plan_version(
  p_owner_id uuid,
  p_class_id bigint,
  p_version_id bigint
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  snapshot jsonb;
  restored_count integer;
begin
  if exists (
    select 1 from assessment_levels
    where owner_id = p_owner_id and class_id = p_class_id
  ) then
    raise exception '평가수준이 입력된 학급은 평가계획 버전을 복원할 수 없습니다.';
  end if;

  select plan into snapshot
  from assessment_plan_versions
  where id = p_version_id
    and owner_id = p_owner_id
    and class_id = p_class_id;

  if snapshot is null then
    raise exception '복원할 평가계획 버전을 찾지 못했습니다.';
  end if;

  delete from assessment_plans
  where owner_id = p_owner_id and class_id = p_class_id;

  insert into assessment_plans(
    subject, unit, goal, domain, assessment_type, perspective,
    high, middle, low, caution, sort_order, owner_email, owner_id, class_id
  )
  select
    item.subject, item.unit, item.goal, item.domain, item.assessment_type, item.perspective,
    item.high, item.middle, item.low, item.caution, item.sort_order,
    (select owner_email from classrooms where id = p_class_id and owner_id = p_owner_id),
    p_owner_id,
    p_class_id
  from jsonb_to_recordset(snapshot) as item(
    subject text, unit text, goal text, domain text, assessment_type text, perspective text,
    high text, middle text, low text, caution text, sort_order integer
  );

  get diagnostics restored_count = row_count;
  return restored_count;
end;
$$;

revoke all on function restore_assessment_plan_version(uuid, bigint, bigint) from public, anon, authenticated;
