create table if not exists pilot_feedback (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  before_minutes integer not null check (before_minutes between 1 and 3000),
  actual_minutes integer not null check (actual_minutes between 1 and 3000),
  usable_percent integer not null check (usable_percent between 0 and 100),
  satisfaction integer not null check (satisfaction between 1 and 5),
  reuse_intent boolean not null,
  feedback text not null default '',
  submitted_at timestamptz not null default now()
);
create index if not exists pilot_feedback_owner_class_submitted_idx on pilot_feedback(owner_id, class_id, submitted_at desc);
alter table pilot_feedback enable row level security;
revoke all on pilot_feedback from anon, authenticated;
