create table if not exists school_organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists school_members (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references school_organizations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  role text not null default 'teacher' check (role in ('admin', 'teacher')),
  status text not null default 'invited' check (status in ('invited', 'active')),
  invited_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (organization_id, email)
);

create index if not exists school_members_user_id_idx on school_members(user_id);
create index if not exists school_members_email_idx on school_members(email);

alter table school_organizations enable row level security;
alter table school_members enable row level security;
revoke all on school_organizations, school_members from anon, authenticated;
