create table if not exists shared_assessment_plans (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references school_organizations(id) on delete cascade,
  name text not null,
  school_year integer not null,
  semester integer not null check (semester in (1, 2)),
  grade integer not null check (grade between 1 and 6),
  plan jsonb not null,
  item_count integer not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_by_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, school_year, semester, grade, name)
);

create index if not exists shared_assessment_plans_org_idx on shared_assessment_plans(organization_id, school_year, semester, grade);
alter table shared_assessment_plans enable row level security;
revoke all on shared_assessment_plans from anon, authenticated;
