create table if not exists classroom_collaborators (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references school_organizations(id) on delete cascade,
  class_id bigint not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  collaboration_role text not null check (collaboration_role in ('homeroom', 'subject')),
  subjects jsonb not null default '[]'::jsonb,
  can_manage_students boolean not null default false,
  invited_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (class_id, user_id)
);

create index if not exists classroom_collaborators_user_idx on classroom_collaborators(user_id);
create index if not exists classroom_collaborators_class_idx on classroom_collaborators(class_id);
alter table classroom_collaborators enable row level security;
revoke all on classroom_collaborators from anon, authenticated;
