create table if not exists generated_comment_parts (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  student_id bigint not null,
  subject text not null,
  assessment_index integer not null,
  evidence text not null default '',
  sentence text not null default '',
  status text not null default 'needs_review'
    check (status in ('complete', 'warning', 'needs_review')),
  issues jsonb not null default '[]'::jsonb,
  attempts integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (class_id, student_id, subject, assessment_index)
);

create index if not exists generated_comment_parts_owner_class_idx
  on generated_comment_parts(owner_id, class_id, subject, student_id);

alter table generated_comment_parts enable row level security;
revoke all on generated_comment_parts from anon, authenticated;
