alter table generation_jobs drop constraint if exists generation_jobs_job_type_check;
alter table generation_jobs add constraint generation_jobs_job_type_check
  check (job_type in ('comments', 'behaviors', 'comment-pools'));

create table if not exists comment_pool_versions (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  subject text not null,
  unit text not null default '',
  domain text not null,
  level text not null check (level in ('상', '중', '하')),
  criterion text not null,
  level_criteria jsonb not null default '{}'::jsonb,
  canonical_sentence text not null,
  status text not null default 'needs_generation'
    check (status in ('needs_generation', 'generating', 'usable', 'ready', 'failed')),
  target_count integer not null default 20 check (target_count between 1 and 20),
  approved_count integer not null default 0 check (approved_count between 0 and 20),
  generator_version text not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists comment_pool_sentences (
  id bigint generated by default as identity primary key,
  pool_version_id bigint not null references comment_pool_versions(id) on delete cascade,
  sentence text not null,
  normalized_sentence text not null,
  status text not null default 'approved' check (status in ('approved', 'retired')),
  source text not null default 'generated' check (source in ('generated', 'canonical', 'teacher_edited')),
  quality_score numeric(4, 3),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (pool_version_id, normalized_sentence)
);

create table if not exists assessment_plan_pool_links (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  assessment_plan_id bigint not null references assessment_plans(id) on delete cascade,
  pool_version_id bigint not null references comment_pool_versions(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (owner_id, class_id, assessment_plan_id, pool_version_id)
);

create index if not exists comment_pool_versions_lookup_idx
  on comment_pool_versions(subject, domain, level, fingerprint);
create index if not exists comment_pool_sentences_pool_idx
  on comment_pool_sentences(pool_version_id, status);
create index if not exists assessment_plan_pool_links_class_idx
  on assessment_plan_pool_links(owner_id, class_id, assessment_plan_id);

alter table comment_pool_versions enable row level security;
alter table comment_pool_sentences enable row level security;
alter table assessment_plan_pool_links enable row level security;
revoke all on comment_pool_versions, comment_pool_sentences, assessment_plan_pool_links from anon, authenticated;
