create table if not exists teachers (
  email text primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  display_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists classrooms (
  id bigint generated by default as identity primary key,
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  school_name text not null,
  school_year integer not null,
  semester integer not null,
  grade integer not null,
  class_number integer not null,
  created_at timestamptz not null default now(),
  unique (owner_email, school_year, semester, grade, class_number)
);

create table if not exists assessment_plans (
  id bigint generated by default as identity primary key,
  subject text not null,
  unit text not null,
  goal text not null,
  domain text not null,
  assessment_type text not null,
  perspective text not null,
  high text not null,
  middle text not null,
  low text not null,
  caution text not null,
  sort_order integer not null,
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  class_id bigint not null,
  unique (class_id, subject, unit, goal)
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  number integer not null,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  class_id bigint not null,
  unique (class_id, number)
);

create table if not exists assessment_levels (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  subject text not null,
  assessment_index integer not null,
  level text not null check (level in ('상', '중', '하', '-')),
  updated_at timestamptz not null default now(),
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  class_id bigint not null,
  unique (class_id, student_id, subject, assessment_index)
);

create table if not exists generated_comments (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  subject text not null,
  comment text not null,
  updated_at timestamptz not null default now(),
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  class_id bigint not null,
  unique (class_id, student_id, subject)
);

create table if not exists student_behaviors (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  characteristic text not null,
  behavior text not null,
  updated_at timestamptz not null default now(),
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  class_id bigint not null,
  unique (class_id, student_id)
);

alter table teachers enable row level security;
alter table classrooms enable row level security;
alter table assessment_plans enable row level security;
alter table students enable row level security;
alter table assessment_levels enable row level security;
alter table generated_comments enable row level security;
alter table student_behaviors enable row level security;

revoke all on teachers, classrooms, assessment_plans, students, assessment_levels, generated_comments, student_behaviors from anon, authenticated;
