create table if not exists teachers (
  email text primary key,
  user_id uuid unique references auth.users(id) on delete cascade,
  display_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists classrooms (
  id bigint generated by default as identity primary key,
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  school_name text not null,
  school_year integer not null,
  semester integer not null,
  grade integer not null,
  class_number integer not null,
  created_at timestamptz not null default now(),
  unique (owner_email, school_year, semester, grade, class_number)
);

create table if not exists assessment_plans (
  id bigint generated by default as identity primary key,
  subject text not null,
  unit text not null,
  goal text not null,
  domain text not null,
  assessment_type text not null,
  perspective text not null,
  high text not null,
  middle text not null,
  low text not null,
  caution text not null,
  sort_order integer not null,
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  class_id bigint not null,
  unique (class_id, subject, unit, goal)
);

create table if not exists students (
  id bigint generated by default as identity primary key,
  number integer not null,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  class_id bigint not null,
  unique (class_id, number)
);

create table if not exists assessment_levels (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  subject text not null,
  assessment_index integer not null,
  level text not null check (level in ('상', '중', '하', '미응시', '평가 예정', '-')),
  updated_at timestamptz not null default now(),
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  class_id bigint not null,
  unique (class_id, student_id, subject, assessment_index)
);

create table if not exists generated_comments (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  subject text not null,
  comment text not null,
  confirmed boolean not null default false,
  confirmed_at timestamptz,
  evidence_status text not null default 'unchecked' check (evidence_status in ('unchecked', 'pass', 'review')),
  evidence_issues jsonb not null default '[]'::jsonb,
  evidence_hash text,
  evidence_validated_at timestamptz,
  updated_at timestamptz not null default now(),
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  class_id bigint not null,
  unique (class_id, student_id, subject)
);

create table if not exists student_behaviors (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  characteristic text not null,
  behavior text not null,
  confirmed boolean not null default false,
  confirmed_at timestamptz,
  updated_at timestamptz not null default now(),
  owner_email text not null,
  owner_id uuid references auth.users(id) on delete cascade,
  class_id bigint not null,
  unique (class_id, student_id)
);

alter table teachers enable row level security;
alter table classrooms enable row level security;
alter table assessment_plans enable row level security;
alter table students enable row level security;
alter table assessment_levels enable row level security;
alter table generated_comments enable row level security;
alter table student_behaviors enable row level security;

revoke all on teachers, classrooms, assessment_plans, students, assessment_levels, generated_comments, student_behaviors from anon, authenticated;

create table if not exists ai_usage_events (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  feature text not null,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_events_owner_created_idx on ai_usage_events(owner_id, created_at desc);
alter table ai_usage_events enable row level security;
revoke all on ai_usage_events from anon, authenticated;

create table if not exists record_revisions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  record_type text not null check (record_type in ('comment', 'behavior')),
  student_id bigint not null,
  subject text not null default '',
  content text not null,
  characteristic text not null default '',
  confirmed boolean not null default false,
  source text not null,
  created_at timestamptz not null default now()
);

create index if not exists record_revisions_lookup_idx on record_revisions(owner_id, class_id, record_type, student_id, subject, created_at desc);
alter table record_revisions enable row level security;
revoke all on record_revisions from anon, authenticated;

create table if not exists generation_jobs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  job_type text not null check (job_type in ('comments', 'behaviors')),
  status text not null check (status in ('queued', 'running', 'completed', 'completed_with_errors', 'failed', 'cancelled')),
  batches jsonb not null default '[]'::jsonb,
  current_batch integer not null default 0,
  total_batches integer not null default 0,
  total_items integer not null default 0,
  completed_items integer not null default 0,
  failed_items integer not null default 0,
  error_message text not null default '',
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists generation_jobs_owner_class_created_idx on generation_jobs(owner_id, class_id, created_at desc);
create unique index if not exists generation_jobs_one_active_idx on generation_jobs(owner_id, class_id, job_type) where status in ('queued', 'running');
alter table generation_jobs enable row level security;
revoke all on generation_jobs from anon, authenticated;

create table if not exists assessment_plan_versions (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  source text not null,
  label text not null,
  plan jsonb not null default '[]'::jsonb,
  item_count integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists assessment_plan_versions_lookup_idx on assessment_plan_versions(owner_id, class_id, created_at desc);
alter table assessment_plan_versions enable row level security;
revoke all on assessment_plan_versions from anon, authenticated;

create table if not exists pilot_feedback (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  owner_email text not null,
  class_id bigint not null,
  before_minutes integer not null check (before_minutes between 1 and 3000),
  actual_minutes integer not null check (actual_minutes between 1 and 3000),
  usable_percent integer not null check (usable_percent between 0 and 100),
  satisfaction integer not null check (satisfaction between 1 and 5),
  reuse_intent boolean not null,
  feedback text not null default '',
  submitted_at timestamptz not null default now()
);
create index if not exists pilot_feedback_owner_class_submitted_idx on pilot_feedback(owner_id, class_id, submitted_at desc);
alter table pilot_feedback enable row level security;
revoke all on pilot_feedback from anon, authenticated;
