allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
verifyDepsBeforeRun: false
trustLockfile: true
nodeLinker: hoisted
minimumReleaseAgeExclude:
  - '@next/eslint-plugin-next@16.2.12'
  - eslint-config-next@16.2.12
  - '@next/env@16.2.12'
  - '@next/swc-darwin-arm64@16.2.12'
  - '@next/swc-darwin-x64@16.2.12'
  - '@next/swc-linux-arm64-gnu@16.2.12'
  - '@next/swc-linux-arm64-musl@16.2.12'
  - '@next/swc-linux-x64-gnu@16.2.12'
  - '@next/swc-linux-x64-musl@16.2.12'
  - '@next/swc-win32-arm64-msvc@16.2.12'
  - '@next/swc-win32-x64-msvc@16.2.12'
  - next@16.2.12
  - esbuild@0.28.1
  - postcss@8.5.18
  - ws@8.21.0
  - vite@8.0.16
  - undici@7.28.0
  - sharp@0.35.0
  - react-server-dom-webpack@19.2.8
overrides:
  esbuild@<0.25.0: ^0.25.12
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  postcss@<=8.5.17: ^8.5.18
  sharp@<0.35.0: ^0.35.0
  undici@>=7.0.0 <7.28.0: ^7.28.0
  ws@>=8.0.0 <8.21.0: ^8.21.0
