CREATE TABLE `assessment_plans` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`subject` text NOT NULL,
	`unit` text NOT NULL,
	`goal` text NOT NULL,
	`domain` text NOT NULL,
	`assessment_type` text NOT NULL,
	`perspective` text NOT NULL,
	`high` text NOT NULL,
	`middle` text NOT NULL,
	`low` text NOT NULL,
	`caution` text NOT NULL,
	`sort_order` integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `assessment_plans_content_idx` ON `assessment_plans` (`subject`,`unit`,`goal`);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('국어', '1. 생생하게 표현해요', '상황에 알맞은 표정과 몸짓, 목소리나 말투로 표현할 수 있다.', '듣기·말하기', '서술형 평가, 구술 평가', '인물의 상황에 알맞은 표정, 몸짓, 목소리, 말투를 알고 있는가? / 인물의 상황에 알맞은 표정, 몸짓, 목소리, 말투를 활용해 표현할 수 있는가?', '작품 속 인물들의 상황에 알맞은 표정, 몸짓, 목소리, 말투를 알고, 작품 속 인물들의 대화를 실감 나게 표현할 수 있다.', '작품 속 인물들의 상황에 알맞은 표정, 몸짓, 목소리, 말투를 알고, 작품 속 인물들의 대화를 표현할 수 있다.', '작품 속 인물들의 상황에 알맞은 표정, 몸짓, 목소리, 말투를 알고, 작품 속 인물들의 대화를 표현하기 위해 노력한다.', '인물의 상황에 알맞은 표정, 몸짓, 목소리, 말투가 다양할 수 있음을 고려한다. / 평가 결과는 보충·심화 학습의 판단 자료로 활용할 수 있다.', 1);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('국어', '2. 분명하고 유창하게', '문장의 짜임을 생각하며 문장을 바르게 표현할 수 있다.', '문법', '서술형 평가', '문장을 문장의 짜임에 따라 나눌 수 있는가? / 자료에 대한 내용을 문장의 짜임에 맞게 표현할 수 있는가?', '문장을 문장의 짜임에 따라 나눌 수 있고, 자료에 대한 내용을 문장의 짜임에 맞게 표현할 수 있다.', '문장을 문장의 짜임에 따라 일부 나눌 수 있고, 자료에 대한 내용을 문장의 짜임에 맞게 일부 표현할 수 있다.', '교사의 도움을 받아 문장을 문장의 짜임에 따라 나누고, 자료에 대한 내용을 문장의 짜임에 맞게 표현할 수 있다.', '그림 자료에 대한 해석은 다양할 수 있음을 고려한다. / 평가 결과는 보충·심화 학습의 판단 자료로 활용할 수 있다.', 2);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('국어', '3. 짜임새 있는 글, 재미와 감동이 있는 글', '작품에서 느낀 재미나 감동을 다양하게 표현할 수 있다.', '문학', '서술형 평가, 포트폴리오 평가', '작품을 읽고 재미나 감동을 느낀 부분과 그 까닭이 무엇인지 쓸 수 있는가? / 작품에서 느낀 재미나 감동을 그림이나 시 등으로 표현할 수 있는가?', '작품을 읽고 재미나 감동을 느낀 부분과 그 까닭이 무엇인지 쓰고, 재미나 감동을 느낀 부분이 잘 드러나도록 다양한 방법으로 표현할 수 있다.', '작품을 읽고 재미나 감동을 느낀 부분과 그 까닭이 무엇인지 쓸 수 있다.', '교사의 도움을 받아 작품을 읽고 재미나 감동을 느낀 부분과 그 까닭이 무엇인지 쓸 수 있다.', '재미나 감동을 느낀 부분이 잘 드러나도록 표현했는지 유의하여 평가한다. / 평가 결과는 보충·심화 학습의 판단 자료로 활용할 수 있다.', 3);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('국어', '4. 중요한 내용을 찾아요', '설명하는 글을 읽고 중심 문장과 뒷받침 문장을 파악하여 글의 내용을 간추릴 수 있다.', '읽기', '서술형 평가', '설명하는 글을 읽고 중심 문장과 뒷받침 문장을 파악할 수 있는가? / 중심 문장을 생각하며 글의 내용을 간추릴 수 있는가?', '설명하는 글을 읽고 중심 문장과 뒷받침 문장을 파악하여 글의 내용을 이해하기 쉽게 간추릴 수 있다.', '설명하는 글을 읽고 중심 문장과 뒷받침 문장을 파악하여 글의 내용을 간추릴 수 있다.', '설명하는 글을 읽고 교사의 도움을 받아 중심 문장과 뒷받침 문장을 파악하여 글의 내용을 간추릴 수 있다.', '중심 문장을 활용해 글을 간추렸는지 유의하여 평가한다. / 평가 결과는 보충·심화 학습의 판단 자료로 활용할 수 있다.', 4);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('국어', '5. 인물에게 마음을 전해요', '마음을 전하는 글을 쓰는 방법을 활용하여 마음을 전하는 글을 쓸 수 있다.', '쓰기', '서술형 평가', '마음을 전하는 글을 쓰는 방법을 알고 있는가? / 마음을 전하는 글을 쓸 수 있는가?', '마음을 전하는 글을 쓰는 방법을 알고, 활용하여 전하고자 하는 마음이 잘 드러나도록 글을 쓸 수 있다.', '마음을 전하는 글을 쓰는 방법을 알고, 마음을 전하는 글을 쓰기 위해 노력한다.', '교사의 도움을 받아 마음을 전하는 글을 쓰는 방법을 알고, 마음을 전하는 글을 쓴다.', '마음을 전하는 글 쓰는 방법을 활용했는지 유의하여 평가한다. / 평가 결과는 보충·심화 학습의 판단 자료로 활용할 수 있다.', 5);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('사회', '1. 우리가 사는 곳', '우리가 사는 곳에 있는 여러 장소를 소개할 수 있다.', '지리 인식', '구술, 상호 평가', '우리가 사는 곳의 여러 장소를 소개하는 여러 방법 중 하나를 골라 표현할 수 있는가? / 우리가 사는 곳의 여러 장소를 모둠원과 협력하며 소개할 수 있는가?', '우리가 사는 곳의 여러 장소를 소개하는 여러 방법 중 한 가지를 골라 소개 자료를 만들고, 이를 소개한다.', '모둠원의 도움을 받아 우리가 사는 곳의 장소 소개 자료를 만들고 소개한다.', '모둠원의 도움을 받아 우리가 사는 곳의 장소 소개 자료를 만든다.', '모둠별 활동을 하되 활동지는 개별로 나누어 주어 각각 쓰도록 한다. / 6~7차시와 연계 지도 시, 우리가 사는 곳의 여러 장소를 어떻게 효과적으로 표현하는지에 대한 평가가 이루어질 수 있도록 한다.', 6);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('사회', '1. 우리가 사는 곳', '우리가 생각하는 살기 좋은 곳의 조건을 바른 자세로 토의할 수 있다.', '지속 가능한 세계', '토의·토론, 논술형', '내가 생각하는 살기 좋은 곳의 조건과 그 이유를 말할 수 있는가? / 모둠원들과 토의하며 살기 좋은 곳의 조건을 정리할 수 있는가?', '내가 생각하는 살기 좋은 곳의 조건과 그 이유를 한 가지 말하고, 친구들의 생각을 들으며 바른 자세로 토의에 임한다.', '내가 생각하는 살기 좋은 곳의 조건과 그 이유를 한 가지 말하고, 토의에 참여한다.', '친구들의 생각을 들으며 토의에 참여한다.', '살기 좋은 곳의 조건에 대한 서로의 생각이 다를 수 있음을 이해할 수 있도록 지도한다. / 살기 좋은 곳의 조건에 대한 토의 결과를 공유할 때, 이유를 들어 설명하도록 하고 평가한다.', 7);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('사회', '2. 일상에서 만나는 과거', '과거의 물건을 조사하고 정리할 수 있다.', '역사 일반', '토의·토론, 조사 보고서', '오래된 물건을 조사하는 다양한 방법을 알고 있는가? / 오래된 물건의 쓰임, 관련 있는 당시 사람들의 생활 모습을 조사할 수 있는가?', '오래된 물건을 조사하는 다양한 방법을 알고 오래된 물건을 조사한 후 정리할 수 있다.', '물건을 조사하는 방법을 알고 모둠원의 도움을 받아 오래된 물건을 조사한다.', '모둠원의 도움을 받아 오래된 물건을 조사한다.', '오래된 물건을 조사하는 방법을 알고 이를 실제로 적용할 수 있는지를 살펴본다. / 관찰 평가를 통해 모둠원이 협동하여 과제를 수행하는지 살펴본다.', 8);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('사회', '2. 일상에서 만나는 과거', '지역에 전해 내려오는 옛이야기를 조사해 지역의 유래를 알 수 있다.', '지역사', '구술, 조사 보고서', '지역에 전해 내려오는 옛이야기를 조사할 수 있는가? / 지역의 이름에 담긴 유래와 특징을 찾을 수 있는가?', '지역 이름의 유래와 옛이야기를 조사하여 정리하고 글로 표현한다.', '모둠원의 도움을 받아 지역 이름의 유래와 옛이야기를 조사하고 글로 표현한다.', '모둠원의 도움을 받아 지역 이름의 유래와 옛이야기를 조사한다.', '교과서 121쪽 염포동의 유래를 살펴보는 활동을 하면서 옛이야기를 통해 지명의 유래를 확인할 수 있음을 이해하였는지 파악한 후 평가를 진행한다. / 지명의 유래를 조사하는 방법(지역 안내 서적 탐색, 답사, 인터넷 검색 서비스 이용 등)을 사전에 지도한 후 평가한다.', 9);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('도덕', '2. 성실하게 사는 삶', '성실한 생활의 사례를 탐색하고, 성실하게 살아가기 위한 자세와 태도를 다질 수 있다.', '자신과의 관계', '서술형 평가', '성실한 생활의 사례를 탐색할 수 있는가? / 성실하게 살아가기 위한 자세와 태도를 다질 수 있는가?', '성실한 생활의 사례를 탐색하고, 성실하게 살아가기 위한 자세와 태도를 다질 수 있다.', '성실한 생활의 사례를 탐색하고, 성실하게 살아가기 위한 자세와 태도를 다지기 위해 노력한다.', '교사의 도움을 받아 성실한 생활의 사례를 탐색하고, 성실하게 살아가기 위한 자세와 태도를 다지기 위해 노력한다.', '성실과 관련 있게 작성한 경우 예시 답안과 다르더라도 맞는 것으로 인정하여 평가한다. / 평가 결과는 보충·심화 학습의 판단 자료로 활용할 수 있다.', 10);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('도덕', '3. 함께하는 우리 가족', '효·우애의 의미를 이해하고, 가족을 소중히 여기는 마음을 전할 수 있다.', '타인과의 관계', '서술형 평가', '효·우애의 의미를 이해하고 있는가? / 가족을 소중히 여기는 마음을 전할 수 있는가?', '효·우애의 의미를 이해하고, 실천할 수 있는 일을 비교적 알고 있으며 가족을 소중히 여기는 마음을 전할 수 있다.', '효·우애의 의미를 이해하고, 가족을 소중히 여기는 마음을 전할 수 있다.', '교사의 도움을 받아 효·우애의 의미를 이해하고, 가족을 소중히 여기는 마음을 전하기 위해 노력한다.', '성실하게 답한 경우 인정하여 평가한다. / 평가 결과는 보충·심화 학습의 판단 자료로 활용할 수 있다.', 11);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('수학', '1. 덧셈과 뺄셈', '받아올림이 여러 번 있는 세 자리 수 덧셈의 계산 원리와 형식을 알고, 문제를 해결할 수 있다.', '수와 연산1', '서술형', '받아올림이 여러 번 있는 세 자리 수 덧셈의 계산 원리와 형식을 알고 있는가? / 받아올림이 여러 번 있는 세 자리 수 덧셈 문제를 해결하는가?', '받아올림이 여러 번 있는 세 자리 수 덧셈의 계산 원리와 형식을 알맞게 알고, 문제를 정확하게 해결한다.', '받아올림이 여러 번 있는 세 자리 수 덧셈의 계산 원리와 형식을 알고, 문제를 해결한다.', '받아올림이 여러 번 있는 세 자리 수 덧셈의 계산 원리와 형식을 이해하도록 노력한다.', '1번 문항을 통해 덧셈의 계산 원리와 형식을 알고 있는지 평가한다. / 6번 문항의 경우 식과 답이 모두 정확할 때 정답으로 인정한다.', 12);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('수학', '2. 평면도형', '선분, 반직선, 직선을 구별하고, 알맞게 그을 수 있다.', '도형과 측정2', '서술형', '선분, 반직선, 직선을 구별할 수 있는가? / 선분, 반직선, 직선을 그을 수 있는가?', '선분, 반직선, 직선을 정확하게 구별하고, 알맞게 긋는다.', '선분, 반직선, 직선을 구별하고 긋는다.', '교사의 도움을 받아 선분, 반직선, 직선을 구별한다.', '선분, 반직선, 직선을 그을 때 자를 사용하도록 안내한다.', 13);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('수학', '3. 나눗셈', '나눗셈 상황을 나눗셈식으로 나타내고, 몫을 구할 수 있다.', '수와 연산3', '서술형', '나눗셈 상황을 이해하고 나눗셈식으로 나타낼 수 있는가? / 나눗셈의 몫을 구하고 그 과정을 설명할 수 있는가?', '나눗셈 상황을 이해하여 정확하게 나눗셈식으로 나타내어 몫을 구한 후 과정을 알맞게 설명한다.', '나눗셈 상황을 이해하여 나눗셈식으로 나타내어 몫을 구한다.', '교사의 도움을 받아 나눗셈 상황을 이해하여 나눗셈식으로 나타내고 몫을 구한다.', '1번 문항의 (1), 2번 문항의 (1)로 나눗셈의 해결 원리와 방법을 이해했는지 평가한다. / 1번 문항의 (1)은 각 접시에 과자를 4개씩 담으면, 2번 문항의 (2)는 3개씩 묶어 표시하면 모두 정답으로 인정한다.', 14);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('수학', '4. 곱셈', '올림이 한 번 있는 (몇십몇)×(몇)을 계산할 수 있다.', '수와 연산4', '서술형', '올림이 한 번 있는 (몇십몇)×(몇)의 계산 원리와 방법을 이해하고 있는가? / 올림이 한 번 있는 (몇십몇)×(몇)을 계산할 수 있는가?', '올림이 한 번 있는 (몇십몇)×(몇)의 계산 원리와 방법을 알맞게 이해하고, 정확하게 계산한다.', '올림이 한 번 있는 (몇십몇)×(몇)의 계산 원리와 방법을 이해하고 계산한다.', '교사의 도움을 받아 올림이 한 번 있는 (몇십몇)×(몇)의 계산 원리와 방법을 이해하고 계산한다.', '1~6번 문항으로 올림이 한 번 있는 (몇십몇)×(몇)의 계산 원리와 방법을 이해하고 있는지 평가한다. / 8번 문항은 동수와 지혜가 가진 연필의 수를 각각 구하고, 계산이 알맞다면 모두 정답으로 인정한다.', 15);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('수학', '5. 길이와 시간', '초 단위까지 시각을 읽고, 시간을 다양하게 표현할 수 있다.', '도형과 측정5', '서술형', '초 단위까지 시각을 읽을 수 있는가? / 시간을 ‘몇 분 몇 초’와 ‘몇 초’로 다양하게 표현할 수 있는가?', '초 단위까지 시각을 정확하게 읽고, 시간을 다양하게 표현한다.', '초 단위까지 시각을 읽고 시간을 다양하게 표현한다.', '초 단위까지 시각을 읽고 시간을 표현하기 위해 노력한다.', '1~6번 문항으로 초 단위까지 시각을 읽을 수 있는지, 7~11번 문항으로 시간을 다양하게 표현할 수 있는지 평가한다. / 4~6번 문항은 자를 사용하여 시각을 나타내도록 안내한다.', 16);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('과학', '1. 힘과 우리 생활', '용수철저울을 사용해 무게를 비교할 수 있다.', '운동과 에너지', '실험·실습, 논술형', '용수철저울 각 부분의 이름과 사용 방법을 아는가? / 용수철저울을 사용해 물체의 무게를 비교할 수 있는가?', '용수철저울 각 부분의 이름과 사용 방법을 자세하게 알고, 용수철저울을 사용해 물체의 무게를 정확하게 비교한다.', '용수철저울의 사용 방법을 알고, 용수철저울을 사용해 물체의 무게를 비교적 정확하게 잴 수 있다.', '용수철저울을 사용해 물체의 무게를 비교하는 데 어려움을 겪는다.', '사전에 용수철저울의 사용 방법을 숙지할 수 있도록 실습 기회를 충분히 제공한다. / 용수철저울을 사용하여 무게를 재기에 적당한 물체 몇 가지를 함께 찾아보아도 좋다.', 17);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('과학', '2. 동물의 생활', '동물의 특징을 이용한 생활용품을 설계할 수 있다.', '생명2', '산출물, 자기평가', '생활용품을 설계하는 데 이용할 동물의 특징을 알고 설명하는가? / 동물의 특징을 이용해 생활용품을 창의적으로 설계하는가?', '생활용품을 설계하는 데 이용할 동물의 특징을 잘 알고, 동물의 특징을 이용해 생활용품을 창의적으로 설계한다.', '모둠 친구들과 함께 동물의 특징을 이용해 생활용품을 설계한다.', '모둠에서 동물의 특징을 이용해 생활용품을 설계하는 데 협력을 하지 않는다.', '모둠 활동에서 최대한 갈등이 발생하지 않도록 학생들의 이해와 배려를 도모한다. / 창의적인 설계를 위해 동물의 특징을 이용한 기존 생활용품을 살펴보는 시간을 가져도 좋다.', 18);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('과학', '4. 생물의 한살이', '배추흰나비의 한살이를 관찰하고 글과 그림으로 표현할 수 있다.', '생명3', '논술형, 산출물', '배추흰나비의 한살이인 배추흰나비알, 애벌레, 번데기, 어른벌레의 특징을 설명하는가? / 배추흰나비의 한살이를 글과 그림으로 표현할 수 있는가?', '배추흰나비의 한살이인 배추흰나비알, 애벌레, 번데기, 어른벌레의 특징을 자세하게 설명하고, 배추흰나비의 한살이를 글과 그림으로 잘 표현한다.', '배추흰나비의 한살이를 관찰하고, 배추흰나비의 한살이를 글과 그림으로 간단하게 표현한다.', '배추흰나비의 한살이를 관찰하였으나, 글과 그림으로 표현하지 못한다.', '평소에 작성한 배추흰나비 한살이 관찰 기록장을 참고하도록 허용한다. / 산출물을 전시하여 평가 이후에도 배움이 이루어지도록 한다.', 19);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('음악', '2. 음악을 열어요', '바른 자세와 주법을 익혀 리코더를 연주할 수 있다.', '연주', '실기평가, 관찰평가', '바른 자세와 주법으로 리코더를 연주할 수 있는가?', '바른 자세와 주법으로 리코더를 연주할 수 있다.', '바른 자세와 주법으로 리코더를 천천히 연주할 수 있다.', '교사의 도움을 받아 바른 자세와 주법으로 리코더를 연주하려고 노력한다.', '낮은음의 운지는 처음부터 좋은 소리가 나기 어려운 운지라는 것을 학생들에게 안내하여 흥미를 잃지 않게 지도한다. / 바른 자세와 주법으로 리코더를 연주하는지 평가한다.', 20);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('음악', '2. 음악을 열어요', '음악을 듣고 음악에 사용된 타악기 음색의 특징을 이야기할 수 있다.', '감상', '지필평가, 관찰평가', '음악을 듣고 음악에 사용된 타악기 음색의 특징을 이야기할 수 있는가?', '음악에 사용된 타악기를 구별하여 음색의 특징을 2개 이야기할 수 있다.', '음악에 사용된 타악기를 구별하여 음색의 특징을 1개 이야기할 수 있다.', '교사의 도움을 받아 음악에 사용된 타악기를 구별하고 음색의 특징을 이야기하려고 노력한다.', '음악을 주의 깊게 들으며 여러 가지 타악기의 소리와 특징을 탐색하게 한다. / 충분히 감상할 수 있는 시간과 기회를 제공한다.', 21);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('미술', '3. 수채로 표현하기', '수채화 재료와 용구의 특성과 사용법을 알고 수채 물감의 특성을 살려 표현할 수 있다.', '표현', '자기평가, 실기평가', '수채화 재료와 용구의 특성 및 사용법을 익히고, 수채 물감의 특성을 살려 주제를 효과적으로 표현했는가?', '수채화 재료와 용구의 특성을 정확히 이해하고 사용 방법을 설명할 수 있으며, 다양한 표현 방법을 활용해 주제를 표현하고 수채화 표현 활동에 적극적으로 참여할 수 있다.', '수채화 재료와 용구의 특성을 이해하고 기본적인 사용 방법을 설명할 수 있으며, 기본적인 표현 방법을 활용해 주제를 표현하고 수채화 표현 활동에 참여할 수 있다.', '수채화 재료와 용구의 특성이 있음을 알고, 수채화 재료와 용구를 사용해 주제를 부분적으로 표현하며, 수채화 표현 방법을 탐색하는 데 참여한다.', '사물의 색과 형을 그대로 모사하려는 것이 아니므로 수채화의 표현 방법을 자유롭게 탐색할 수 있도록 한다. / 특정 단계에 치중하지 않고 준비, 표현, 정리 단계의 전반적인 과정 및 태도를 평가한다.', 22);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('미술', '1. 생활 속 미술 만나기', '학교 속에서 다양하게 활용되는 미술을 찾아 그 특징을 발견할 수 있다.', '감상', '연구 보고서법', '학교 속에서 다양하게 활용되는 미술을 찾아 그 특징을 발견할 수 있는가?', '생활 속에서 활용되는 미술의 특징을 이해해 설명할 수 있으며, 생활 속 미술을 탐색하고 다양한 특징을 주도적으로 발견한 뒤 체계적으로 정리하고 자신의 생각을 적극적으로 표현할 수 있다.', '생활 속에서 활용되는 미술의 특징을 이해할 수 있으며, 생활 속 미술을 탐색하고 특징을 발견한 뒤 정리하고 자신의 생각을 표현할 수 있다.', '생활 속 미술을 발견하고 인지하며, 생활 속 미술을 탐색하고 특징을 일부 발견하고 생활 속 미술에 일부 관심을 가진다.', '생활 속 미술을 얼마나 많이 찾았느냐를 양적으로 평가하기보다는 생활 속 미술이 주변에 다양하게 존재함을 인지하고 자기 주도적으로 정리하는 과정을 평가한다.', 23);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('체육', '운동 / 2. 건강 생활 습관', '바른 자세를 알고 실천할 수 있다.', '건강', '관찰법, 체크리스트, 자기평가', '바른 자세를 알고 실천할 수 있는가?', '바른 자세를 생활 속에서 꾸준히 실천할 수 있다.', '바른 자세를 생활 속에서 실천하려고 노력할 수 있다.', '주변의 도움을 받아 바른 자세를 생활 속에서 실천할 수 있다.', '무리하게 운동 계획을 세우는 것보다는 자신에게 맞은 운동 계획을 세우고, 꾸준히 실천하는 과정을 평가한다.', 24);
--> statement-breakpoint
INSERT OR IGNORE INTO assessment_plans (subject, unit, goal, domain, assessment_type, perspective, high, middle, low, caution, sort_order) VALUES ('영어', '1. Hello, ABC!', '알파벳 대·소문자를 구별하여 쓸 수 있다.', '표현', '지필평가, 관찰 평가', '알파벳 대·소문자를 구별하여 쓸 수 있는가?', '알파벳 대·소문자를 정확하게 구별하여 쓴다.', '알파벳 대·소문자를 대체적으로 구별하여 쓴다.', '알파벳 대·소문자를 구별하여 쓰는 데 어려움이 있다.', '알파벳 대·소문자를 구별하여 글자의 모양에 맞게 사선에 쓸 수 있도록 안내한다.', 25);
